### ISSUE TITLE
More Flexible Generated Bash Script

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt-start-script#17]
The restriction that the bash script must be run from the sbt project root is unnecessarily restrictive. A simple enhancement to the generated script would remove this restriction. 

1) Add these two lines to the top of the generated script:

```
DIR=`dirname $BASH_SOURCE`
BASE=`basename $0`
```

Modify this line to use the variables introduced above:

```
test -x "$DIR/$BASE" || die "\"$DIR/$BASE\" not found, this script must be run from the project base directory"
```

2) Replace the leading dot for the generated classes with `$DIR`:

```
exec java $JAVA_OPTS -cp "$DIR/scala-2.9.2/classes:blahblahblah
```

Now the program can be run from any directory IF the project's `target` directory is added to the `PATH`.

**Comment by mslinn** [comment]
This is a better way to computer DIR:

```
if [ $OSTYPE == "cygwin" ]; then
  DIR=`cygpath -m $(dirname $BASH_SOURCE)`
else
  DIR=`dirname $BASH_SOURCE`
fi
```

I'll update my pull request

**Comment by havocp** [comment]
This should be fixed in master.
