### ISSUE TITLE
plugin can not be installed.

### ISSUE THREAD

**Issue by macinux** [sbt/sbt-start-script#23]
Followed the readme and put addSbtPlugin("com.typesafe.sbt" % "sbt-start-script" % "0.X.Y") in the ~/.sbt/plugins/build.sbt.

I got this error when i started sbt
[info] Resolving org.scala-sbt#precompiled-2_10_0-m7;0.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-start-script;0.X.Y: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by havocp** [comment]
Right now it is:
 addSbtPlugin("com.typesafe.startscript" % "xsbt-start-script-plugin" % "0.5.2")

The rename to com.typesafe.sbt sbt-start-script has not been published. The old README at https://github.com/typesafehub/xsbt-start-script-plugin is the one that works for the moment. Sorry about that, need to get the new one published here.

**Comment by havocp** [comment]
Fixed, the new API is now published as 0.6.0 and the README instructions should work.
