### ISSUE TITLE
readlink -f broken on bsd/mac

### ISSUE THREAD

**Issue by havocp** [sbt/sbt-start-script#30]
Reported by @stephenjudkins on commit b64cc549f015dfdd37ffed79aaf5d194a08ff8b1

For possible solutions see 
http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by seadowg** [comment]
When is this fix planned to be released? Would be nice to be able to use start-script on OS X...

**Comment by havocp** [comment]
I did a v0.9.0 just now.

**Comment by seadowg** [comment]
Awesome thanks!
