### ISSUE TITLE
'die' is not a command or bash built-in

### ISSUE THREAD

**Issue by admackin** [sbt/sbt-start-script#32]
If you don't have a main class defined for the project, the generated script includes the 'die' command, which is a Perlism, and not part of Bash. This should probably be replaced by 'echo ERROR_MSG && exit 1'.

**Comment by havocp** [comment]
It's intended to have this in there:

``` sh
function die() {
   echo $* 1>&2
   exit 1
}
```

So the fix is to output that into the script.
