### ISSUE TITLE
Windows generated script gives error

### ISSUE THREAD

**Issue by Chemmo** [sbt/sbt-start-script#37]
I think the quoting is invalid in a generated windows batch script in 0.8.0. The line:

if "%MAINCLASS%"=="" ( echo 'This "start" script requires a main class name as the first argument, because a mainClass was not specified in SBT and not autodetected by SBT (usually means you have zero, or more than one, main classes).  You could specify in your SBT build: mainClass in Compile := Some("Whatever")' && EXIT 1)

gives the error:

. was unexpected at this time.

If the single quotes are replaced by double quotes it works ok. I dont think using single quotes will treat special characters such as parenthesis as part of a character sequence, e.g.

C:>IF "a"=="a" (echo 'blah ("blah") blah' && echo blah)
blah' was unexpected at this time.

C:>IF "a"=="a" (echo "blah ("blah") blah" && echo blah)
'blah "blah" blah'
blah

**Comment by havocp** [comment]
@jchab - thoughts on the right fix?

**Comment by jchab** [comment]
I did some quick testing and it does look like switching the single quotes to double should fix the problem.

**Comment by havocp** [comment]
Thanks! @Chemmo do you want to make a pull request? I can do it "blind" (no Windows) but it might be nicer for someone with Windows to give it a shot and test it.

**Comment by Chemmo** [comment]
I just created a pull request, I'm fairly new to this so let me know if I did something wrong...https://github.com/sbt/sbt-start-script/pull/39. It seems to work ok, but all of the SbtStartScript.startScriptForX settings produce the same output as far as I can tell (I created a separate issue for this https://github.com/sbt/sbt-start-script/issues/38)

**Comment by Chemmo** [comment]
@havocp Can you please merge the pull request? 
Thanks
