### ISSUE TITLE
Wrong delimiter -- colon should be semi-colon 

### ISSUE THREAD

**Issue by KeithPinson** [sbt/sbt-start-script#6]
The generated shell script "start" (on a Windows platform) has "java ... -cp "...classes:C:\Docu...".  The delimiter before "C:" is a colon.  It should be a semi-colon.

**Comment by havocp** [comment]
Thanks for the report, will plan to fix this in the next release.

**Comment by havocp** [comment]
I think this may be fixed in 0.5.1, though I don't have Windows to test.

**Comment by KeithPinson** [comment]
Fixed

Tested:
- xsbt-start-script-plugin set to 0.5.1 in build.sbt
- sbt version set to 0.11.2 in build.properties
- ran on Windows 7
