### ISSUE TITLE
Start script doesn't work with bash on windows

### ISSUE THREAD

**Issue by max-l** [sbt/sbt-start-script#9]
the generated start script uses windows style paths which is not compatible with bash, ex.:

java $JAVA_OPTS -cp "C:\dev\heroku-test\repo\htest\target\scala-2.9.1\classes:c:\dev\heroku-test\home.sbt\boot\scala-

transforming the paths to :  

/C/dev/heroku-test/repo/

will cause it to work.

**Comment by havocp** [comment]
It would probably be ideal to just generate a Windows-native .bat script, right? Doesn't using bash require people to install cygwin or something?

I'm aware that the plugin probably doesn't work on Windows but unfortunately I don't have the right setup to develop and test a windows version... generating a start.bat is hopefully pretty easy, but I need some help with it.

**Comment by max-l** [comment]
Sent a pull request for the fix

**Comment by max-l** [comment]
Is there a snapshot available for this fix, or with the latest state of master ?

**Comment by havocp** [comment]
I finally pushed a new 0.5.1 with this fix, thanks
